{% set name = "neptune-client" %}
{% set version = "0.16.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neptune-ai/neptune-client/archive/{{ version }}.tar.gz
  sha256: ce1d41ba4070ceaa4d70e74c1a09d8f94460b9ae04f71830ecd9ccb44a92e852

build:
  noarch: python
  number: 0
  entry_points:
    - neptune = neptune_cli.main:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bravado
    - bravado-core
    - click >=7.0
    - dataclasses >=0.6
    - future >=0.17.1
    - gitpython >=2.0.8
    - oauthlib >=2.1.0
    - packaging
    - pandas
    - pillow >=1.1.6
    - psutil
    - pyjwt
    - python >=3.6
    - requests >=2.20.0
    - requests-oauthlib >=1.0.0
    - six >=1.12.0
    - urllib3
    - websocket-client >=0.35.0
    - boto3 >=1.16.0
    - swagger-spec-validator >=2.7.4
    - jsonschema <4.0.0

test:
  imports:
    - neptune
    - neptune.internal
    - neptune.internal.backends
    - neptune.internal.channels
    - neptune.internal.execution
    - neptune.internal.hardware
    - neptune.internal.hardware.cgroup
    - neptune.internal.hardware.gauges
    - neptune.internal.hardware.gpu
    - neptune.internal.hardware.metrics
    - neptune.internal.hardware.metrics.reports
    - neptune.internal.hardware.metrics.service
    - neptune.internal.hardware.resources
    - neptune.internal.hardware.system
    - neptune.internal.notebooks
    - neptune.internal.storage
    - neptune.internal.streams
    - neptune.internal.threads
    - neptune.internal.utils
    - neptune.internal.websockets
    - tests.neptune
    - tests.neptune.internal
    - tests.neptune.internal.backends
    - tests.neptune.internal.channels
    - tests.neptune.internal.hardware
    - tests.neptune.internal.hardware.gauges
    - tests.neptune.internal.hardware.metrics
    - tests.neptune.internal.hardware.resources
    - tests.neptune.internal.storage
    - tests.neptune.utils

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client
  doc_url: https://github.com/neptune-ai/neptune-client/blob/master/README.md
  dev_url: https://github.com/neptune-ai/neptune-client

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - shnela
    - Raalsky
    - PK-Neptune
